<!DOCTYPE html>
<html>
<head>
    <title>{{ $title }}</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; font-size: 10px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #000; padding-bottom: 10px; }
        .school-name { font-size: 16px; font-weight: bold; text-transform: uppercase; margin: 0; }
        .report-title { font-size: 14px; margin: 5px 0; color: #555; }
        .dept-badge { font-size: 12px; font-weight: bold; color: #1e40af; margin-top: 5px; }
        
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #f8fafc; color: #475569; text-transform: uppercase; font-size: 8px; border: 1px solid #e2e8f0; padding: 8px; }
        td { border: 1px solid #e2e8f0; padding: 8px; vertical-align: middle; }
        
        .cat-row { background-color: #f1f5f9; font-weight: bold; }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .footer { position: fixed; bottom: 0; width: 100%; font-size: 8px; text-align: right; color: #94a3b8; }
        .negative { color: #dc2626; } /* Optional: Red color for stock out */
    </style>
</head>
<body>

    <div class="header">
        <img src="{{ public_path('logo/ausl.png') }}" style="height: 60px; margin-bottom: 5px;">
        <p class="school-name">Arellano University School of Law</p>
        <p class="report-title uppercase">{{ $title }}</p>
        
        @if(isset($department))
            <div class="dept-badge">OFFICE: {{ strtoupper($department) }}</div>
        @endif
        
        <p style="margin-top: 5px;">Date Generated: {{ now()->format('F d, Y h:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Product Code</th>
                <th>Item Description</th>
                <th>Category</th>
                <th>Personnel</th>
                <th class="text-center">Qty</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transactions as $trx)
                <tr>
                    <td>{{ $trx->created_at->format('M d, Y') }}</td>
                    <td style="font-family: monospace;">{{ $trx->item->product_code }}</td>
                    <td style="font-weight: bold;">{{ strtoupper($trx->item->name) }}</td>
                    <td>{{ $trx->item->category->name }}</td>
                    <td>{{ $trx->released_to ?? $trx->received_by }}</td>
                    <td class="text-center {{ $trx->type === 'Out' ? 'negative' : '' }}" style="font-weight: bold;">
                        {{-- The logic below correctly applies the minus sign --}}
                        {{ $trx->type === 'Out' ? '-' : '+' }}{{ number_format($trx->quantity, 2) }}
                    </td>
                    <td style="font-style: italic; font-size: 8px;">
                        {{ $trx->purpose ?? ($trx->type === 'In' ? 'Restock' : 'Issuance') }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by AU Inventory System | Page <script type="text/php">echo $PAGE_NUM;</script> of <script type="text/php">echo $PAGE_COUNT;</script>
    </div>

</body>
</html>